apiVersion : apps/v1
kind: Deployment
metadata:
  name: "demok8s-e17c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "demok8s-e17c"
  template:
    metadata:
      labels:
        app: "demok8s-e17c"
    spec:
      containers:
        - name: "demok8s-e17c"
          image: "absfsf.azurecr.io/demok8s"
          ports:
          - containerPort: 8080