apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "danademocluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "danademocluster"
    spec:
      containers:
        - name: "danademocluster"
          image: "danademoacr.azurecr.io/danademocluster"
          ports:
          - containerPort: 8080