apiVersion: v1
kind: Service
metadata:
    name: "demok8s-e17c"
    labels:
        app: "demok8s-e17c"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "demok8s-e17c"