on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: actionregistry.azurecr.io
        username: ${{secrets.acr_actionregistry_username}}
        password: ${{secrets.acr_actionregistry_password}}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Application" -f  "Application/Dockerfile" -t actionregistry.azurecr.io/igniteprodaks5557:${{github.sha}}
        docker push actionregistry.azurecr.io/igniteprodaks5557:${{github.sha}}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{secrets.aks_igniteprodaks_kubeConfig}}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep igniteprodaks5557 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace igniteprodaks5557`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: igniteprodaks5557
        container-registry-url: actionregistry.azurecr.io
        container-registry-username: ${{secrets.acr_actionregistry_username}}
        container-registry-password: ${{secrets.acr_actionregistry_password}}
        secret-name: igniteprodakdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: igniteprodaks5557
        manifests: |
          Application/manifests/deployment-5557.yml
          Application/manifests/service-5557.yml
        images: |
          actionregistry.azurecr.io/igniteprodaks5557:${{github.sha}}
        imagepullsecrets: |
          igniteprodakdockerauth