on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: absfsf.azurecr.io
        username: ${{ secrets.acr_absfsf_username }}
        password: ${{ secrets.acr_absfsf_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Application" -f  "Application/Dockerfile" -t absfsf.azurecr.io/demok8s:${{ github.sha }}
        docker push absfsf.azurecr.io/demok8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_demok8s_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep demok8s3d76 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace demok8s3d76`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: demok8s3d76
        container-registry-url: absfsf.azurecr.io
        container-registry-username: ${{ secrets.acr_absfsf_username }}
        container-registry-password: ${{ secrets.acr_absfsf_password }}
        secret-name: demok8sdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: demok8s3d76
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          absfsf.azurecr.io/demok8s:${{ github.sha }}
        imagepullsecrets: |
          demok8sdockerauth